# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# FluidHelloWorld build for CI

pr:
  - main
  - main-azure

pool: "Small"

steps:
  - task: ComponentGovernanceComponentDetection@0
    inputs:
      scanType: "Register"
      verbosity: "Verbose"
      alertWarningLevel: "High"
  - task: UseNode@1
    displayName: Use Node 18.x
    inputs:
      version: 18.x
  - task: Npm@1
    displayName: Install
    inputs:
      command: "custom"
      customCommand: "ci"
  - task: CmdLine@2
    displayName: Build
    inputs:
      script: "npm run build"
  - task: CmdLine@2
    displayName: Lint
    inputs:
      script: "npm run lint"
  - task: CmdLine@2
    displayName: Test
    inputs:
      script: "npm run ci:test"
  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "**/*junit-report.xml"
      searchFolder: "$(System.DefaultWorkingDirectory)"
    condition: succeededOrFailed()
